export const listData = [
    {
      id: 1,
      title: 'A Great Apartment Next to the Beach!',
      img: 'https://cf.bstatic.com/xdata/images/xphoto/1020x340/48387990.jpg?k=16a0f0e62cafbf6f7a75c634c5b8934c99f8bfa8cc40410a6c6880d01ae81426&o=',
      bedRooms: 2,
      bathRooms: 1,
      price: 1000,
      address: '456 Park Avenu, London',
      latitude: 51.5074,
      longitude: -0.1278,
    },
    {
        id: 2,
        title: 'A Great Apartment Next to the Beach!',
        img: 'https://www.londonrelocationconsultancy.com/templates/One-Hyde-Park--002.jpg',
        bedRooms: 3,
        bathRooms: 2,
        price: 1500,
        address: '789 Oxford Street, London',
        latitude: 52.4862,
        longitude: -1.8904,
      },
      {
        id: 3,
        title: 'A Great Apartment Next to the Beach!',
        img: 'https://noblelondon.com/wp-content/uploads/91075.jpg',
        bedRooms: 1,
        bathRooms: 1,
        price: 800,
        address: '101 Baker Street, London',
        latitude: 51.5074,
        longitude: -0.1278,
      },
      {
        id: 4,
        title: 'A Great Apartment Next to the Beach!',
        img: 'https://i.pinimg.com/564x/71/90/8d/71908d307a1a419b619e3998ec6b7812.jpg',
        bedRooms: 3,
        bathRooms: 1,
        price: 1600,
        address: '10-A Green Street, London',
        latitude: 52.0038,
        longitude: -0.1560,
      },
      {
        id: 5,
        title: 'A Great Apartment Next to the Main Bridge!',
        img: 'https://golosua.com/wp-content/uploads/2023/09/kvartira-v-londone.jpg',
        bedRooms: 1,
        bathRooms: 1,
        price: 2000,
        address: '5 Bridge Street, London',
        latitude: 52.5639,
        longitude: -0.2061,
      },
      {
        id: 6,
        title: 'A Great Apartment in the center of the London!',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGf4c7bonxjtuqw19hsOy5hwip6XH0rAegCg&usqp=CAU',
        bedRooms: 4,
        bathRooms: 2,
        price: 3500,
        address: '11-B Capital Street, London',
        latitude: 51.3451,
        longitude: -0.1089,
      },
      {
        id: 7,
        title: 'An Style Apartment in the London!',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC3UkPVWzmsaVTfjtYhTC2OalkNIJ897RLzw&usqp=CAU',
        bedRooms: 2,
        bathRooms: 2,
        price: 2500,
        address: '89 Corner Street, London',
        latitude: 53.2390,
        longitude: -0.3450,
      },
      {
        id: 8,
        title: 'An Style Apartment in the London!',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHf_HeaLcVFvJ_c9DmIAgZLVMjVvCjDIXqhQ&usqp=CAU',
        bedRooms: 1,
        bathRooms: 1,
        price: 1500,
        address: '32 Amazing Street, London',
        latitude: 51.5612,
        longitude: -0.0025,
      },
]